### PR TITLE
Sort templates alphabetically when displaying 'New Mailing'

### LINKED ISSUE #334: Sorting - Design Templates
Amend sorting of templates in 'design' section when creating new mailing to alphabetical order

### PR DESCRIPTION
**Pull request by mattwire**
Fixes #334 @BeccaTregenna

### CODE REVIEW

**Review by BeccaTregenna — COMMENTED** [review]
Hi @mattwire 
Tested and it works for templates but won't sort base - tried by reversing the order to DESC in testing and it doesn't do anything.
Becca

**Comment by mattwire** [comment]
@BeccaTregenna Please could you test this again?  The MosaicoBaseTemplate.Get uses a different method to get the list which doesn't support the sort/limit params - so I've changed it to case-insensitive alphabetical sort instead which seems to be working for me!

**Comment by BeccaTregenna** [comment]
@mattwire Thank you. Changed the ksort to a krsort on my local copy to test and that worked fine for me too. So as far as I'm concerned this is all good.

**Comment by mattwire** [comment]
Merging based on @BeccaTregenna testing and review. Thankyou!

**Pull request merged**
