### PR TITLE
(Experimental) bin/setup.sh - Update to Mosaico v0.16-civicrm-1

### PR DESCRIPTION
**Pull request by totten**
(This is experimental.  DO NOT MERGE.  Provided for possible
reference/collaboration.)

### CODE REVIEW

**Comment by mattwire** [comment]
For reference, also see https://github.com/mattwire/mosaico/tree/master-civicrm-1-mjwconsulting which is a branch tracking mosaico master

**Comment by totten** [comment]
Nice one @mattwire.

**Comment by mattwire** [comment]
@totten Can we close this - it's pretty stale and mosaico upstream has moved on quite a long way

**Comment by totten** [comment]
Good point, @mattwire. Closing.

**Pull request closed without merging**
