### PR TITLE
Image caching performance improvements

### PR DESCRIPTION
**Pull request by rocxa**
Add 30 day caching headers to images (rough length of time email traffic from an email lasts)
Add static imageurls on CiviMail send

### CODE REVIEW

**Comment by deepak-srivastava** [comment]
@rocxa thanks. Looks good. We 'll do some tests mainly for alterMailContent hook, and merge.

**Comment by rocxa** [comment]
@deepak-srivastava 
Should we add directory creation to the config initialisation to avoid the directory problems?

`       
        // Create required directories if they don't exist
        if (!is_dir($mConfig['BASE_DIR'].$mConfig['UPLOADS_DIR'])) {
            mkdir($mConfig['BASE_DIR'].$mConfig['UPLOADS_DIR'], 0775, true);
        }
        if (!is_dir($mConfig['BASE_DIR'].$mConfig['STATIC_DIR'])) {
            mkdir($mConfig['BASE_DIR'].$mConfig['STATIC_DIR'], 0775, true);
        }
        if (!is_dir($mConfig['BASE_DIR'].$mConfig['THUMBNAILS_DIR'])) {
            mkdir($mConfig['BASE_DIR'].$mConfig['THUMBNAILS_DIR'], 0775, true);
        }
`

**Comment by deepak-srivastava** [comment]
@rocxa yep sounds good. Go ahead. 
You might also want to refer to - https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/blob/master/mosaico.php#L38 to make sure it handles any possible failure conditions.

**Comment by deepak-srivastava** [comment]
@rocxa think we should also add some checks in runcheck() too, to report for any cases where directory creation failed for some reason and doesn't exist.

**Comment by rocxa** [comment]
@deepak-srivastava Perhaps runcheck could be run every time mosaico is loaded and the directory creation checks just added to runcheck?

**Comment by deepak-srivastava** [comment]
@rocxa Yep. Lets do that.

**Comment by rocxa** [comment]
@deepak-srivastava I have rewritten the run() function checks and tidied up the formatting of the files.

**Comment by rocxa** [comment]
I'll close this an create a new (cleaner) PR from master.

**Pull request closed without merging**
