### PR TITLE
#410 - Multisite support for mosaico

### PR DESCRIPTION
**Pull request by krishgopi**
- Add domain_id to civicrm_mosaico_template table
- Save domain_id during new template creation
- Display templates specific to the domain in view all templates page
- Instructions to setup upload directory when using multisite setup, to restrict gallery to each domain

Issues addressed:
https://github.com/veda-consulting-company/uk.co.vedaconsulting.mosaico/issues/410
https://github.com/veda-consulting-company/uk.co.vedaconsulting.mosaico/issues/438

### CODE REVIEW

**Comment by andyburnsco** [comment]
Tested creating and editing Mosiaco message templates in my multisite environment

**Comment by mattwire** [comment]
@andyburnsco Does that mean you've tested it and it works?

**Comment by andyburnsco** [comment]
@mattwire yes, so long as this PR matches what we tested on our staging environment. Confirming with @veda-consulting @rajeshrhino

**Comment by andyburnsco** [comment]
@krishgopi see above. What are we waiting on?

**Comment by rajeshrhino** [comment]
We have tested this locally and @andyburnsco has also tested in his staging (multisite) environment.

@mattwire this is ready for review

**Pull request merged**
