### PR TITLE
[WIP] Advanced CiviMail workflow support

### PR DESCRIPTION
**Pull request by monishdeb**
Mail compose screen for different roles.

1. Creator (with `create mailings` permission)
creator

2. Scheduler (with 'schedule mailings' permission)
scheduler

3. Approver (with 'approve mailings' permission)
approve

4. Access Mailing permission: 
accessmailing

### CODE REVIEW

**Comment by colemanw** [comment]
@monishdeb this needs rebase

**Comment by mattwire** [comment]
@monishdeb This seems like a nice feature. Do you plan to continue working on it?

**Comment by monishdeb** [comment]
@mattwire yes I'll resume my work and let you know after testing the patch in the next few days.

**Comment by mattwire** [comment]
@monishdeb I'm going to close this - please reopen if/when you have a reviewable PR

**Pull request closed without merging**
