### PR TITLE
CRM-21100 Alter loading of unsubscribe groups and preview groups to be dynamic …

### PR DESCRIPTION
**Pull request by seamuslee001**
…to reduce DOM Load and add performance improvements

This aims to remove some custom handling for groups and to replicate changes made here https://github.com/civicrm/civicrm-core/pull/10898/files that have been accepted into core. 

ping @totten

### CODE REVIEW

**Comment by deepak-srivastava** [comment]
@seamuslee001 seems like one file is in conflict -  ang/crmMosaico/BlockPreview.html 

@totten any comments?

**Comment by seamuslee001** [comment]
@deepak-srivastava have fixed the conflict now i believe

**Comment by mattwire** [comment]
@seamuslee001 Quick question.. does this add a minimum core version dependency?

**Comment by seamuslee001** [comment]
@mattwire i don't believe so but its just about making sure `crm-entityref` is there which i think is certainly there in the 4.7 series but i basically worked off code. This code should be making it less dependent on core by using more API than preloaded objects @colemanw

**Comment by colemanw** [comment]
This looks right to me :)
@mattwire `entityRef` is also in 4.6 so this shouldn't change the version requirements.

**Comment by mattwire** [comment]
@totten @deepak-srivastava So I think this one can be merged...

**Pull request merged**
