### PR TITLE
Add setting to hide base templates

### PR DESCRIPTION
**Pull request by elcapo**
This is a merge request that attempts to fix the problem described in issue #241. In particular, it adds a new setting called `mosaico_hide_base_templates` that allows setting a list of template ids to be hidden. In the screenshot, the setting is being used to hide 2 of the 3 base templates:

Screenshot_2020-12-07 Mosaico Settings

**Important Note:**

When hiding a template, also messages that were created using it won't be shown. Therefore, some use cases are:

1. if you're only using `versafix-1`, you can safely disable `tedc15` and `tutorial`,
2. if you're only using a custom template (as [CiviVersafix](https://lab.civicrm.org/MikeyMJCO/CiviVersafix/)), you can also safely disable `versafix-1`.

If you decided to hide the 3 templates and you don't install a custom one, you won't leave any available template to work with.

### CODE REVIEW

**Comment by mattwire** [comment]
@elcapo Does this also work with the custom templates directory?

**Comment by elcapo** [comment]
> @elcapo Does this also work with the custom templates directory?

Sorry for the late answer. Yes, it does!

**Comment by elcapo** [comment]
I've also switched the UI to a slightly more usable multiple selector:

Screenshot from 2021-01-28 13-18-19

Also, to facilitate the revision of the changes, it might be useful to check the `findBaseTemplates` method of the `CRM_Mosaico_BAO_MosaicoTemplate` class, as I added two parameters to it.

By default, it works as it always did. But by using those parameters we can now:

- call the method skipping the cache by passing it the first `$ignoreCache` as true
- disable the hooks execution by passing it the second `$dispatchHooks` as false

This is important because what the extension is doing here is basically to alter the way it creates the list of base templates:

- when using it to show the templates in the mailing editor, it will work as always,
- but when using the same method (with the parameters described above) for the options of templates to hide, it will also show the hidden ones.

**Comment by homotechsual** [comment]
This is working great for me in testing. I like the multiselect UI option.

**Pull request merged**
