### PR TITLE
Introduce A/B testing for subject lines

### PR DESCRIPTION
**Pull request by totten**
Before
=====

Creating an A/B test with Mosaico content is pretty cumbersome -- e.g. make a standalone Mosaico template; then enable the msg-tpl sync; then make an A/B test; and in the content of the test, use the msg-tpl; and don't try to change any of the content in the tpl.

After
====

In the "New Mailing" screen, the subject line shows a "+" button.

Screen Shot 2019-11-25 at 8 38 31 PM

Clicking the "+" button will create a few more fields -- for the alternative subjects and the sample sizing.

Screen Shot 2019-11-25 at 8 39 10 PM

Comments
============

Some interesting bits:

* The composition screen uses Mosaico UI - and content can be rearranged in-situ with Mosaico
* This should work in `crm-*` and in Shoreditch.
* When you send a test mailing, you'll get two emails (one with each variant)
* When you submit/finalize the Mosaico blast, it is converted to a formal CiviMail A/B test. The standard CiviMail UI already provides a set of links/reports/workflows for tracking A/B test mailings, and these will work the same on the Mosaico A/B mailings.

### CODE REVIEW

**Comment by mattwire** [comment]
Hey @totten What's the status of this - mergeable, or should we close?

**Comment by mattwire** [comment]
@totten Please re-open if you plan on working on this :-)

**Comment by nganivet** [comment]
@totten How much work would be needed to merge this in master?

**Comment by larssandergreen** [comment]
@totten Also interested in knowing what's required to get this merged. I think this would be of interest to a lot of folks.

**Comment by eileenmcnaughton** [comment]
I just re-opened o check the state - seems stale

**Comment by colemanw** [comment]
@totten can you rebase this?

**Comment by nganivet** [comment]
To note: my client suggested to replace the (+) sign icon with a (A/B test) or similar wording on the button for better clarity. Thanks.

**Comment by nganivet** [comment]
@totten @colemanw Seems like a waste that we've financed this development and it now sits there without being merged in core. This is a prestigious feature for CiviCRM, it's been in CiviMail but was still lacking in Mosaico. What would be needed to close and merge this?

**Comment by colemanw** [comment]
@nganivet I agree we should get this merged in. If we can rebase it this week, will you have time to test it so we can get it merged?

**Comment by nganivet** [comment]
@colemanw Yes, I will test it with my client's configuration within a week after being rebased. If testing is conclusive, I am pretty sure my client would agree to deploy it in production for more extensive testing.

**Comment by larssandergreen** [comment]
@colemanw We would also be willing to test in production after @nganivet's initial testing.

**Comment by totten** [comment]
Thanks @nganivet @larssg-wildsight. I'd like to see this reviewed/merged too!

The branch is rebased and should be reviewable. 

Some notes:

* Most of the patches re-applied with minimal merge-conflicts. ✅ 
* The main snag was re-generating the CSS files -- this had quietly regressed in the main branch. I eventually settled on #403 to make it build. That's included with the updated branch (so it's probably outta-site/outta-mind from y'all's perspective).
* The phpunit test-suite is passing ✅ 
* I did a quick/light mail-blast locally. It seemed to send the A/B and the final C components. ✅

There were two quirks that I noticed, but they're not related to this PR (e.g. they're problems with or without this PR) and don't affect the modified artifacts.

* The editor screen is a little overzealous about confirming when you lave the page -- see #400 
* If one is using the Shoreditch UI v0.1-alpha35, there's some extra red lines on the second step of the wizard layout. These look fine on earlier versions like alpha12, alpha20, and alpha33.

The main thing outstanding for A/B is some second-party testing. Let us know if it works (or doesn't)!

**Comment by mattwire** [comment]
@totten You should be able to rebase against master now I've merged the other two PRs

**Comment by totten** [comment]
Nice, thanks @mattwire. I've rebased again and pushed up.

**Comment by nganivet** [comment]
@totten Thanks, will test as soon as possible. Client is currently on 5.19.4 with FlexMailer 1.1.1, Mosaico 2.3, Shoreditch alpha 37. Do I just need to update Mosaico to this branch or are there other dependencies? In core?

**Comment by colemanw** [comment]
@nganivet this PR doesn't modify any dependencies in `info.xml` so it's probably safe to assume it will run on that stack.

**Comment by larssandergreen** [comment]
This appears to be working well in general, thanks everyone.

One small issue: on the results page for the A/B test, the number of tracked opens isn't updating. It just shows N/A, even though there are many tracked opens (clicking through shows the actual results).

I've checked this with a traditional mailing and it shows N/A until a click is recorded and then starts showing the actual number of clicks, so it seems something specific to Mosaico is happening here.

Screen Shot 2020-10-06 at 10 47 24 AM

5.28.4 with Flexmailer 1.1.1 and Shoreditch 1.0.0-beta.2

**Comment by eileenmcnaughton** [comment]
I'm going to merge this & suggest someone addresses the NaaN as a follow up. This is a big chunk of work & I think it might be easier to manage if the bulk is merged - given the bulk seems mergeable

**Comment by nganivet** [comment]
We have deployed to production today after some cursory testing over the past few days (20-100 emails/mailing). All great so far! 

Thanks @mattwire @totten @colemanw @larssg-wildsight and @eileenmcnaughton for driving this past the finish line!!!

**Comment by nganivet** [comment]
@totten we should do a blog post on this as it is a major feature. How would you like to proceed?
I will ask my client if the org would like to be credited.

**Comment by eileenmcnaughton** [comment]
@nganivet yay! do we need to fix the issue @larssg-wildsight found first?

**Comment by nganivet** [comment]
IMO not critical to fix prior to release, it's probably very minor. I will keep you updated if there is any end-user feedback on my end, but am not expecting any since they have already been using this feature for a year now.

**Comment by eileenmcnaughton** [comment]
@nganivet OK - I think @mattwire & I (as well as @veda-consulting ) have rights to tag a release - we should maybe tag as is against 5.28 as that has been tested & then test on 5.31 over the next week or so since there is an angular update in there

**Comment by larssandergreen** [comment]
@nganivet Are you saying you're not seeing the issue I'm seeing on your end? Just to be clear, I'm not seeing any issue with non-Mosaico A/B tests (nor was it a problem before), but am seeing it with Mosaico A/B tests. If it's just me, that's all fine, but if it's more general, it seems like a bit of a show stopper as the opens count is the key number people would look at to pick which subject they want to use.

**Comment by nganivet** [comment]
@larssg-wildsight my client is not using the metric 'tracked open' as usually unreliable, and just looks at the clicks to compare mailing's success. This is why I stated it is not critical for my client, but I understand it might be for you and you'd like this fixed prior to release. Let's work towards this then.

@eileenmcnaughton @totten FYI, the Tracked Opens was working prior to this merge, but the Unsubscribes wasn't.
image

**Comment by larssandergreen** [comment]
I think this should go ahead.

It turns out the opens do show up a number of hours later. The issue is that the opens are being recorded in UTC and I'm in UTC-7, so they don't show up until 7 hours later, [as discussed here.](https://civicrm.stackexchange.com/questions/27778/why-do-click-and-open-reports-show-times-in-utc-rather-than-the-sites-timezone/27909) There must be something that is correcting for this for traditional mailings, but not here in Mosaico A/B testing. Should I create a separate issue for this?

**Comment by eileenmcnaughton** [comment]
@larssg-wildsight yes - a separate issue makes sense - note there are some factors in play

1) have all the relevant fields been translated to timestamps - I think status checks will show if not and
2) is the url people are clicking on using the extern patch (with extern in the url)

**Pull request merged**
