### PR TITLE
Mosaico general improvements

### PR DESCRIPTION
**Pull request by meladawy**
This PR contain a general UI & UX improvements to Mosaico Extension.

### CODE REVIEW

**Comment by guanhuan** [comment]
Hi @deepak-srivastava ,

This PR including the major styling fixes we did in the past a few weeks. Most of the non-Mosaico-specific styling issues are fixed in the Shoreditch extension and have been merged. Please take a look and merge if no problem.

Many thanks.

Guanhuan

**Comment by totten** [comment]
General reactions:
 * I like the new template-item layout. Actually, all the new layouts in the screenshots look nice. :)
 * Adding the gupfile / scss is a change in the developer experience and needs some communication. You should  add a couple lines to the README about gulp/scss (near "Development: Setup.sh").
 * Looking at the commit history, it seems like the dev workflow went awry -- because a lot of PR review happened in a non-canonical repo. Of course, I'm glad review was being done. But it should have been routed through the canonical repo (`veda-consulting/uk.co.vedaconsulting.mosaico`) as smaller PRs/in-real-time -- sending a large bundle after-the-fact makes it harder to understand/review.

**Comment by meladawy** [comment]
Hey @totten, 
Yea i agree with you this is confusing to have all those commits at once. I'll avoid this for the upcoming changes. I also updated the README file, please have a look and let me know if you have any comments/questions. 

https://github.com/compucorp/uk.co.vedaconsulting.mosaico/blob/f7031e5fbb74525bc107d622a315387dbdcd2800/README.md

**Comment by totten** [comment]
@meladawy README update looks perfect. :+1:

**Pull request merged**
