### PR TITLE
Fix for links being made relative, breaking mailings

### PR DESCRIPTION
**Pull request by JKingsnorth**
This is based on suggestions in #165 and should fix:
#165 and #156

### CODE REVIEW

**Comment by mattwire** [comment]
Do you expect this to fix https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/issues/160 as well?

**Comment by JKingsnorth** [comment]
I'll check tomorrow unless you beat me to it ☺️

**Comment by bhahumanists** [comment]
Ooh, that's a good fix. Nice work.

**Comment by JKingsnorth** [comment]
Dev server was down this morning but I'll test the image URL issue this
afternoon.

**Comment by JKingsnorth** [comment]
Credit goes to @bhahumanists for finding the solution in #165 

This PR doesn't seem to fix the social icons issue, but I'm working on that now (in a separate issue).

This is ready for review.

**Comment by mattwire** [comment]
See PR #182 for social icons fix

**Comment by mattwire** [comment]
@JKingsnorth Confirmed that your fix seems to work - now have it running on a new client site.

**Comment by monishdeb** [comment]
@JKingsnorth confirmed that this fix works for me.. where earlier links were changed to relative now and it's taking the absolute url.

**Pull request merged**
