### PR TITLE
Updated README and set default

### PR DESCRIPTION
**Pull request by guanhuan**
- Updated README to structure installation options better and include v2 info
 - Set default setting via the correct method

### CODE REVIEW

**Comment by guanhuan** [comment]
Hi @deepak-srivastava , 

Can we please have a pre-release of 2.0-beta2 when this is merged? 

Thanks!

**Comment by veda-consulting** [comment]
Sure, Deepak is back in the office on Monday and we can get it sorted for
you then.

**Comment by deepak-srivastava** [comment]
@totten @guanhuan do i need to hold beta2 till https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/pull/151 is fixed?

**Comment by guanhuan** [comment]
@deepak-srivastava I don't think approach discussion is worth to hold off the whole beta 2. Truth is the updated README won't allow community users to setup Mosaico easily until we release the beta 2 (see option 1). So I would suggest to release it anyway but @totten and @meladawy can continue work out the details of the approach and I will sign off before we tag official release.

**Comment by deepak-srivastava** [comment]
@guanhuan thanks.
@totten I've tagged 2.0-beta2. Should be ready for publish, once build is ready with dist.civicrm.org?

**Comment by deepak-srivastava** [comment]
2.0-beta2 seems to have got published - https://civicrm.org/extensions/email-template-builder.
Date is incorrect, but it could be due to incorrect date in info file.

**Pull request merged**
