### PR TITLE
Mark Mosaico 2 stable

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
@veda-consulting @deepak-srivastava @totten mattermost discussions amounted to 'there are no more blockers' - shall we do it!

### CODE REVIEW

**Comment by francescbassas** [comment]
Maybe it is still necessary to go through a beta5 because there is no release since jun 2018 and there are significant changes like https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/pull/281.

**Comment by MarshCastle** [comment]
Just through curiosity - can this be marked as stable if the dependencies aren't yet stable?

**Comment by eileenmcnaughton** [comment]
I believe that's circular - @totten told me flex mailer isn't stable because mosaico isn't

**Comment by mattwire** [comment]
Let's just mark it stable! Dependencies can follow. Date in the info.xml will need updating too...

**Comment by francescbassas** [comment]
> Just installed Mosaico 1.1 for CiviCRM 5.7.2 on Drupal 7.

See https://civicrm.stackexchange.com/q/28466/104

**Review by mattwire — CHANGES_REQUESTED** [review]
Note the release date needs updating before release...

**Comment by mattwire** [comment]
@totten @deepak-srivastava @veda-consulting Any progress on this - can we mark what we've got as 2.0 stable?

We're going to need to increment min version soon to support things like this: https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/pull/299 so now seems like a good time...

**Comment by mattwire** [comment]
Merged via #300

**Pull request closed without merging**
