### PR TITLE
Add A/B testing for email design

### PR DESCRIPTION
**Pull request by totten**
# Overview

Expands support for A/B testing.

~~This is currently marked "Draft" because there are a couple TODOs (noted at bottom of PR). However, it should work well enough that one can do some testing.~~ (*Resolved*)

ping @kurund 

# Before

* You may add a second "Subject" field, which enables A/B testing. (By default, it copies your current subject.)

# After

* You may add a second "Subject" field, which enables A/B testing. (By default, it copies your current subject.)
* You may add a second "Design" section, which enables A/B testing. (By default, it copies your current design.)

    Screenshot 2024-02-01 at 10 32 08 PM

    After doing this, you will see "Design (A)" and "Design (B)".

    Screenshot 2024-02-01 at 10 28 56 PM

* It is possible to mix/match testing at the "Subject"-level and the "Design"-level.  The GUI provides separate options for enabling/disabling each of these. These should be working in both "Single Page" and "Wizard" layouts.

* (Aside: I moved the "A/B testing" percentage-sliders toward the end of the "New Mailing" screen. When there are multiple ways to enable A/B testing, it's a bit confusing if the sliders popup *earlier* in the UI. The new placement ensures that the sliders appear you've made all the decisions about whether to test subject and/or design.)

# Technical Details

Within a `Mailing` record, there is a section `template_options.variants[0,1]`. The existing `AbDemux` component reads this property and generates "A" and "B" mailings (if present). This is how the `subject`-testing works. This PR follows the same path for testing two values of `body_html`. The existing `AbDemuxTest` already has scenarios for [multiple `body_html` variants](https://github.com/veda-consulting-company/uk.co.vedaconsulting.mosaico/blob/3.3/tests/phpunit/CRM/Mosaico/AbDemuxTest.php#L63-L66).

Here are a few examples of how the content ought to look:

<details><summary>Example: JSON for single subject and single design</summary>

```javascript
{
  id: 123,
  subject: "Apples are the best fruit",
  body_html: "<html>...yummy...</html>",
  template_options: {
    mosaicoTemplate: "basic-versafix-1",
    mosaicoMetadata: "{...}",
    mosaicoContent: "{...yummy...}"
  }
}
```

</details>

<details><summary>Example: JSON for dual subject and dual design</summary>

```javascript
{
  id: 123,
  subject: "PLACEHOLDER",
  body_html: "PLACEHOLDER",
  template_options: {
    variants: [
      {
        subject: "Apples are the best fruit",
        body_html: "<html>...yummy apple...</html>",
        mosaicoTemplate: "basic-versafix-1",
        mosaicoMetadata: "{...}",
        mosaicoContent: "{...yummy apple...}"
      },
      {
        subject: "Bananas are the best fruit",
        body_html: "<html>...yummy banana...</html>",
        mosaicoTemplate: "basic-versafix-1",
        mosaicoMetadata: "{...}",
        mosaicoContent: "{...yummy banana...}"
      }

    ]
  }
}
```

</details>

In comparing the examples, observe:

* If the `subject` is tested, then we move `subject` into `mailing.template_options.variants.[0,1].subject`.
* If the `body_html` (w/`mosaicoContent`, etc) is tested, then we move the `body_html` (w/`mosaicoContent`, etc) into `mailing.template_options.variants.[0,1].body_html`.

Most of the work in developing this PR has been about updating web UI to consistently populate+cleanup the data in `template_options.variants` (based on whether the user activates `subject` and/or `body_html` variations).

# TODO

* ~~When you use editor, there are options to "Preview" (in browser) or "Send test" (via email). This is basically working for "Send test" (*but not stress-tested yet*). However, the "Preview" is not yet working.~~
* ~~Submit a mailing and try out the full flow of two blasts (followed by third/final blast).~~

### CODE REVIEW

**Comment by totten** [comment]
OK, I fixed the "Preview" issue and clarified the "Send test email" behavior. A trial-run with three deliveries (A+B+Winner) went fine.

It should be good for review/testing.

**Comment by seamuslee001** [comment]
@johntwyman you were saying :)

**Comment by kurund** [comment]
@totten 

Thank you for the work. 

A/B version for the message seems be working as expected. However, I don't see an option for selecting A/B for `From`. Am I missing something?

**Comment by mattwire** [comment]
Merging based on discussion with @totten

**Comment by totten** [comment]
Thanks @kurund. I hadn't realized the `From` was also a target. It shouldn't be big a change (*probably a few hours; a lot easier than the template body/metadata*). So we'll go at that in a follow-up PR.

**Comment by kurund** [comment]
@totten 

Ok thanks.

**Pull request merged**
